export const data = JSON.parse("{\"key\":\"v-672afe6e\",\"path\":\"/netty/advance/protocol.html\",\"title\":\"协议设计与解析\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"协议设计与解析\",\"author\":\"vingkin\",\"date\":\"2022-07-27T00:00:00.000Z\",\"description\":\"为什么需要协议？ TCP/IP 中消息传输基于流的方式，没有边界。 协议的目的就是划定消息的边界，制定通信双方要共同遵守的通信规则 例如：在网络上传输 下雨天留客天留我不留\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vingkin.github.io/Blog/netty/advance/protocol.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Vingkin的学习博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"协议设计与解析\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"为什么需要协议？ TCP/IP 中消息传输基于流的方式，没有边界。 协议的目的就是划定消息的边界，制定通信双方要共同遵守的通信规则 例如：在网络上传输 下雨天留客天留我不留\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"vingkin\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-27T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"协议设计与解析\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-07-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"vingkin\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"为什么需要协议？\",\"slug\":\"为什么需要协议\",\"link\":\"#为什么需要协议\",\"children\":[]},{\"level\":2,\"title\":\"redis 协议举例\",\"slug\":\"redis-协议举例\",\"link\":\"#redis-协议举例\",\"children\":[]},{\"level\":2,\"title\":\"http 协议举例\",\"slug\":\"http-协议举例\",\"link\":\"#http-协议举例\",\"children\":[]},{\"level\":2,\"title\":\"自定义协议要素\",\"slug\":\"自定义协议要素\",\"link\":\"#自定义协议要素\",\"children\":[{\"level\":3,\"title\":\"编解码器\",\"slug\":\"编解码器\",\"link\":\"#编解码器\",\"children\":[]},{\"level\":3,\"title\":\"什么时候可以加 @Sharable💡\",\"slug\":\"什么时候可以加-sharable💡\",\"link\":\"#什么时候可以加-sharable💡\",\"children\":[]}]}],\"git\":{},\"readingTime\":{\"minutes\":5.67,\"words\":1702},\"filePathRelative\":\"netty/advance/protocol.md\",\"localizedDate\":\"2022年7月27日\",\"excerpt\":\"<h2> 为什么需要协议？</h2>\\n<p>TCP/IP 中消息传输基于流的方式，没有边界。</p>\\n<p>协议的目的就是划定消息的边界，制定通信双方要共同遵守的通信规则</p>\\n<p>例如：在网络上传输</p>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>下雨天留客天留我不留\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"copyright\":{\"author\":\"vingkin\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
