export const data = JSON.parse("{\"key\":\"v-60788202\",\"path\":\"/guide/interview/Idempotency.html\",\"title\":\"幂等性\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"幂等性\",\"author\":\"Vingkin\",\"date\":\"2022-06-05T00:00:00.000Z\",\"description\":\"幂等性如何实现？带你了解一波！！！ 所谓幂等性通俗的将就是一次请求和多次请求同一个资源产生相同的副作用。用数学语言表达就是f(x)=f(f(x))。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vingkin.github.io/Blog/Blog/guide/interview/Idempotency.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Vingkin的学习博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"幂等性\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"幂等性如何实现？带你了解一波！！！ 所谓幂等性通俗的将就是一次请求和多次请求同一个资源产生相同的副作用。用数学语言表达就是f(x)=f(f(x))。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2023-09-25T02:33:51.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Vingkin\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-06-05T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2023-09-25T02:33:51.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"幂等性\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-06-05T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2023-09-25T02:33:51.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Vingkin\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"为什么需要幂等性\",\"slug\":\"为什么需要幂等性\",\"link\":\"#为什么需要幂等性\",\"children\":[]},{\"level\":2,\"title\":\"HTTP的幂等性\",\"slug\":\"http的幂等性\",\"link\":\"#http的幂等性\",\"children\":[]},{\"level\":2,\"title\":\"幂等性的实现方式\",\"slug\":\"幂等性的实现方式\",\"link\":\"#幂等性的实现方式\",\"children\":[]}],\"git\":{\"createdTime\":1695609231000,\"updatedTime\":1695609231000,\"contributors\":[{\"name\":\"Vingkin\",\"email\":\"1830053226@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":4.22,\"words\":1265},\"filePathRelative\":\"guide/interview/Idempotency.md\",\"localizedDate\":\"2022年6月5日\",\"excerpt\":\"<blockquote>\\n<p><a href=\\\"https://mp.weixin.qq.com/s?__biz=Mzg5NjMxMTYxNQ==&amp;mid=2247488050&amp;idx=1&amp;sn=1ab9d27793c9bc4698eb35949631a738&amp;source=41#wechat_redirect\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">幂等性如何实现？带你了解一波！！！</a></p>\\n</blockquote>\\n<p>所谓幂等性通俗的将就是一次请求和多次请求同一个资源产生相同的副作用。用数学语言表达就是f(x)=f(f(x))。</p>\",\"copyright\":{\"author\":\"Vingkin\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
