export const data = JSON.parse("{\"key\":\"v-c5a54474\",\"path\":\"/guide/interview/SpringMVC.html\",\"title\":\"SpringMVC\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"SpringMVC\",\"author\":\"Vingkin\",\"date\":\"2022-04-24T00:00:00.000Z\",\"description\":\"什么是MVC MVC是一种设计模式，在这种模式下软件被分为三层，及Model（模型）、View（视图）、Controller（控制器）。Model代表的是数据，View代表的是用户界面，Controller代表的是数据的处理逻辑，它是Model和View这两层的桥梁。将软件分层的好处是，可以将对象之间的耦合度降低，便于代码的维护。 DAO层是做什么的 DAO层是Data Access Object的缩写，即数据访问对象，在项目中它通常作为独立的一层，专门用于访问数据库。 介绍一下Spring MVC的执行流程\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vingkin.github.io/Blog/guide/interview/SpringMVC.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Vingkin的学习博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"SpringMVC\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"什么是MVC MVC是一种设计模式，在这种模式下软件被分为三层，及Model（模型）、View（视图）、Controller（控制器）。Model代表的是数据，View代表的是用户界面，Controller代表的是数据的处理逻辑，它是Model和View这两层的桥梁。将软件分层的好处是，可以将对象之间的耦合度降低，便于代码的维护。 DAO层是做什么的 DAO层是Data Access Object的缩写，即数据访问对象，在项目中它通常作为独立的一层，专门用于访问数据库。 介绍一下Spring MVC的执行流程\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Vingkin\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-04-24T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"SpringMVC\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-04-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Vingkin\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"什么是MVC\",\"slug\":\"什么是mvc\",\"link\":\"#什么是mvc\",\"children\":[]},{\"level\":2,\"title\":\"DAO层是做什么的\",\"slug\":\"dao层是做什么的\",\"link\":\"#dao层是做什么的\",\"children\":[]},{\"level\":2,\"title\":\"介绍一下Spring MVC的执行流程\",\"slug\":\"介绍一下spring-mvc的执行流程\",\"link\":\"#介绍一下spring-mvc的执行流程\",\"children\":[]},{\"level\":2,\"title\":\"说一说你知道的Spring MVC注解\",\"slug\":\"说一说你知道的spring-mvc注解\",\"link\":\"#说一说你知道的spring-mvc注解\",\"children\":[]},{\"level\":2,\"title\":\"介绍一下Sprig MVC的拦截器\",\"slug\":\"介绍一下sprig-mvc的拦截器\",\"link\":\"#介绍一下sprig-mvc的拦截器\",\"children\":[]}],\"git\":{},\"readingTime\":{\"minutes\":4.59,\"words\":1378},\"filePathRelative\":\"guide/interview/SpringMVC.md\",\"localizedDate\":\"2022年4月24日\",\"excerpt\":\"<h2> 什么是MVC</h2>\\n<p>MVC是一种设计模式，在这种模式下软件被分为三层，及<strong>Model（模型）、View（视图）、Controller（控制器）</strong>。Model代表的是数据，View代表的是用户界面，Controller代表的是数据的处理逻辑，它是Model和View这两层的桥梁。将软件分层的好处是，可以将对象之间的耦合度降低，便于代码的维护。</p>\\n<h2> DAO层是做什么的</h2>\\n<p>DAO层是Data Access Object的缩写，即数据访问对象，在项目中它通常作为独立的一层，专门用于访问数据库。</p>\\n<h2> 介绍一下Spring MVC的执行流程</h2>\",\"copyright\":{\"author\":\"Vingkin\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
