<template><div><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/sayit.jpg" style="zoom: 200%;" />
<blockquote>
<p>整理自同济子豪兄</p>
</blockquote>
<h2 id="网络结构" tabindex="-1"><a class="header-anchor" href="#网络结构" aria-hidden="true">#</a> 网络结构</h2>
<figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518135951221.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518142711194.png" alt="image-20220518142711194" tabindex="0" loading="lazy"><figcaption>image-20220518142711194</figcaption></figure>
<h2 id="backbone-darknet-53" tabindex="-1"><a class="header-anchor" href="#backbone-darknet-53" aria-hidden="true">#</a> Backbone（Darknet-53）</h2>
<p>对于输入为<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>256</mn><mo>∗</mo><mn>256</mn></mrow><annotation encoding="application/x-tex">256*256</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">256</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">256</span></span></span></span>的图像，其Backbone如下图所示：</p>
<figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518135554800.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="neck" tabindex="-1"><a class="header-anchor" href="#neck" aria-hidden="true">#</a> Neck</h2>
<p>neck部分就是多尺度特征融合的过程。其中<code v-pre>concat</code>就是在上采样之后，将相同尺度的特征沿通道方向摞起来。就像将相同大小的作业本摞起来。</p>
<h2 id="head" tabindex="-1"><a class="header-anchor" href="#head" aria-hidden="true">#</a> Head</h2>
<p>YOLOv3的head部分，受到了特征金字塔的启发，使用了多尺度特征。</p>
<p>对于输入是<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>416</mn><mo>∗</mo><mn>416</mn></mrow><annotation encoding="application/x-tex">416*416</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">416</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">416</span></span></span></span>的图像，产生<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>13</mn><mo>∗</mo><mn>13</mn><mo separator="true">,</mo><mn>26</mn><mo>∗</mo><mn>26</mn><mo separator="true">,</mo><mn>52</mn><mo>∗</mo><mn>52</mn></mrow><annotation encoding="application/x-tex">13*13,26*26,52*52</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">13</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.8389em;vertical-align:-0.1944em;"></span><span class="mord">13</span><span class="mpunct">,</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord">26</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.8389em;vertical-align:-0.1944em;"></span><span class="mord">26</span><span class="mpunct">,</span><span class="mspace" style="margin-right:0.1667em;"></span><span class="mord">52</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">52</span></span></span></span>三个尺度的特征。其中小尺度特征（比如<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>13</mn><mo>∗</mo><mn>13</mn></mrow><annotation encoding="application/x-tex">13*13</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">13</span><span class="mspace" style="margin-right:0.2222em;"></span><span class="mbin">∗</span><span class="mspace" style="margin-right:0.2222em;"></span></span><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">13</span></span></span></span>）负责预测大物体，大尺度特征负责预测小物体。因为小尺度每个<code v-pre>grid ceil</code>对应更大的感受野。</p>
<p>三个尺度的特征，每个特征的<code v-pre>grid ceil</code>都会生成<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>3</mn></mrow><annotation encoding="application/x-tex">3</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">3</span></span></span></span>个<code v-pre>anchor</code>，一共<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>9</mn></mrow><annotation encoding="application/x-tex">9</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">9</span></span></span></span>个<code v-pre>anchor</code>。其中在<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mn>9</mn></mrow><annotation encoding="application/x-tex">9</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.6444em;"></span><span class="mord">9</span></span></span></span>个<code v-pre>anchor</code>中，与<code v-pre>ground truth</code>的<code v-pre>IOU</code>最大的<code v-pre>anchor</code>负责预测这个<code v-pre>ground truth</code>。</p>
<h2 id="正负样本" tabindex="-1"><a class="header-anchor" href="#正负样本" aria-hidden="true">#</a> 正负样本</h2>
<p>假设<code v-pre>IOU</code>阈值为0.5，其中与<code v-pre>ground truth</code>的<code v-pre>IOU</code>小于阈值的<code v-pre>anchor</code>为<strong>负样本</strong>。超过阈值，且与<code v-pre>ground truth</code>的<code v-pre>IOU</code>最大的<code v-pre>anchor</code>为<strong>正样本</strong>。查过阈值，但是与<code v-pre>ground truth</code>的<code v-pre>IOU</code>不是最大的<code v-pre>anchor</code><strong>既不是正样本也不是负样本</strong>。</p>
<h2 id="损失函数" tabindex="-1"><a class="header-anchor" href="#损失函数" aria-hidden="true">#</a> 损失函数</h2>
<div class="language-latex line-numbers-mode" data-ext="latex"><pre v-pre class="language-latex"><code><span class="token equation string">$$
<span class="token equation-command regex">\begin</span>{equation} <span class="token equation-command regex">\lambda</span>_{coord}<span class="token equation-command regex">\sum</span>_{i=0}^{S^2}<span class="token equation-command regex">\sum</span>_{j=0}^{B}<span class="token equation-command regex">\mathbb</span>{1}_{i,j}^{obj}<span class="token equation-command regex">\cdot</span>[(b_x-<span class="token equation-command regex">\hat</span>{b_x})^2 + (b_y-<span class="token equation-command regex">\hat</span>{b_y})^2 + (b_w-<span class="token equation-command regex">\hat</span>{b_w})^2 +(b_h-<span class="token equation-command regex">\hat</span>{b_h})^2] <span class="token equation-command regex">\\</span> <span class="token equation-command regex">\\</span> <span class="token equation-command regex">\\</span> + <span class="token equation-command regex">\quad</span> <span class="token equation-command regex">\sum</span>_{i=0}^{S^2}<span class="token equation-command regex">\sum</span>_{j=0}^{B}<span class="token equation-command regex">\mathbb</span>{1}_{i,j}^{obj}<span class="token equation-command regex">\cdot</span>[-log(p_c)+<span class="token equation-command regex">\sum</span>_{i=1}^{n}{BCE(<span class="token equation-command regex">\hat</span>{c_i},c_i)}] <span class="token equation-command regex">\\</span> <span class="token equation-command regex">\\</span> <span class="token equation-command regex">\\</span> + <span class="token equation-command regex">\quad</span> <span class="token equation-command regex">\lambda</span>_{noobj}<span class="token equation-command regex">\sum</span>_{i=0}^{S^2}<span class="token equation-command regex">\sum</span>_{j=0}^{B}<span class="token equation-command regex">\mathbb</span>{1}_{i,j}^{noobj}<span class="token equation-command regex">\cdot</span>[-log(1-p_c)] <span class="token equation-command regex">\end</span>{equation}
$$</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518143441409.png" alt="" tabindex="0" loading="lazy"><figcaption></figcaption></figure>
<h2 id="训练过程" tabindex="-1"><a class="header-anchor" href="#训练过程" aria-hidden="true">#</a> 训练过程</h2>
<figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518144159747.png" alt="image-20220518144159747" tabindex="0" loading="lazy"><figcaption>image-20220518144159747</figcaption></figure>
<h2 id="测试过程" tabindex="-1"><a class="header-anchor" href="#测试过程" aria-hidden="true">#</a> 测试过程</h2>
<figure><img src="https://vingkin-1304361015.cos.ap-shanghai.myqcloud.com/深度学习/image-20220518144241994.png" alt="image-20220518144241994" tabindex="0" loading="lazy"><figcaption>image-20220518144241994</figcaption></figure>
<h2 id="附录" tabindex="-1"><a class="header-anchor" href="#附录" aria-hidden="true">#</a> 附录</h2>
<h3 id="官方" tabindex="-1"><a class="header-anchor" href="#官方" aria-hidden="true">#</a> 官方</h3>
<p><strong>YOLOV3目标检测Demo视频</strong>：<a href="https://www.youtube.com/watch?v=MPU2HistivI" target="_blank" rel="noopener noreferrer">https://www.youtube.com/watch?v=MPU2HistivI<ExternalLinkIcon/></a></p>
<p><a href="https://pjreddie.com/darknet/yolo/" target="_blank" rel="noopener noreferrer">https://pjreddie.com/darknet/yolo/<ExternalLinkIcon/></a></p>
<p><a href="https://github.com/pjreddie/darknet" target="_blank" rel="noopener noreferrer">https://github.com/pjreddie/darknet<ExternalLinkIcon/></a></p>
<p><strong>论文地址</strong>：<a href="https://arxiv.org/abs/1804.02767" target="_blank" rel="noopener noreferrer">https://arxiv.org/abs/1804.02767<ExternalLinkIcon/></a></p>
<h3 id="博客" tabindex="-1"><a class="header-anchor" href="#博客" aria-hidden="true">#</a> 博客</h3>
<p><strong>江大白</strong>：<a href="https://zhuanlan.zhihu.com/p/143747206" target="_blank" rel="noopener noreferrer">https://zhuanlan.zhihu.com/p/143747206<ExternalLinkIcon/></a></p>
<p><strong>郭冠华</strong>：<a href="https://zhuanlan.zhihu.com/p/40332004" target="_blank" rel="noopener noreferrer">https://zhuanlan.zhihu.com/p/40332004<ExternalLinkIcon/></a></p>
<p><strong>Netron可视化YOLOV3网络结构</strong>：<a href="https://blog.csdn.net/nan355655600/article/details/106246355" target="_blank" rel="noopener noreferrer">https://blog.csdn.net/nan355655600/article/details/106246355<ExternalLinkIcon/></a></p>
<p><strong>木盏</strong>：<a href="https://blog.csdn.net/leviopku/article/details/82660381" target="_blank" rel="noopener noreferrer">https://blog.csdn.net/leviopku/article/details/82660381<ExternalLinkIcon/></a></p>
<p><strong>太阳花的小绿豆</strong>：<a href="https://blog.csdn.net/qq_37541097/article/details/81214953" target="_blank" rel="noopener noreferrer">https://blog.csdn.net/qq_37541097/article/details/81214953<ExternalLinkIcon/></a></p>
<p><strong>B站工程师Algernon鉴黄YOLO</strong>：<a href="https://github.com/thisiszhou/SexyYolo" target="_blank" rel="noopener noreferrer">https://github.com/thisiszhou/SexyYolo<ExternalLinkIcon/></a></p>
<p><strong>B站工程师Algernon博客</strong>：<a href="https://zhuanlan.zhihu.com/p/76802514" target="_blank" rel="noopener noreferrer">https://zhuanlan.zhihu.com/p/76802514<ExternalLinkIcon/></a></p>
<p><strong>损失函数</strong>：<a href="https://blog.csdn.net/qq_34795071/article/details/92803741" target="_blank" rel="noopener noreferrer">https://blog.csdn.net/qq_34795071/article/details/92803741<ExternalLinkIcon/></a></p>
<h3 id="代码复现" tabindex="-1"><a class="header-anchor" href="#代码复现" aria-hidden="true">#</a> 代码复现</h3>
<p><strong>Ultralytics公司</strong>：<a href="https://github.com/ultralytics/yolov3" target="_blank" rel="noopener noreferrer">https://github.com/ultralytics/yolov3<ExternalLinkIcon/></a></p>
<p><a href="https://github.com/qqwweee/keras-yolo3" target="_blank" rel="noopener noreferrer">https://github.com/qqwweee/keras-yolo3<ExternalLinkIcon/></a></p>
<p><a href="https://github.com/bubbliiiing/yolo3-pytorch" target="_blank" rel="noopener noreferrer">https://github.com/bubbliiiing/yolo3-pytorch<ExternalLinkIcon/></a></p>
<p><strong>cvpods</strong>：<a href="https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/modeling/meta_arch/yolov3.py" target="_blank" rel="noopener noreferrer">https://github.com/Megvii-BaseDetection/cvpods/blob/master/cvpods/modeling/meta_arch/yolov3.py<ExternalLinkIcon/></a></p>
<h3 id="ms-coco目标检测数据集80个类别" tabindex="-1"><a class="header-anchor" href="#ms-coco目标检测数据集80个类别" aria-hidden="true">#</a> MS COCO目标检测数据集80个类别</h3>
<p><strong>交通</strong>：人、自行车、汽车、摩托车、飞机、公交车、火车、卡车、船</p>
<p><strong>市政</strong>：红绿灯、消防栓、STOP标志、停车收费米表、长椅</p>
<p><strong>动物</strong>：鸟、猫、狗、马、绵羊、奶牛、大象、熊、斑马、长颈鹿</p>
<p><strong>随身物品</strong>：双肩背包、雨伞、手提包、领带、行李箱</p>
<p><strong>运动</strong>：飞盘、雪橇、滑雪板、篮球、风筝、棒球棒、棒球手套、滑板、冲浪板、网球拍</p>
<p><strong>器皿餐具</strong>：瓶子、玻璃酒杯、茶杯、叉子、餐刀、勺子、碗</p>
<p><strong>食物</strong>：香蕉、苹果、三明治、橘子、西兰花、胡萝卜、热狗、匹萨、甜甜圈、蛋糕</p>
<p><strong>家具</strong>：椅子、沙发、盆栽、床、餐桌、厕所、电视、笔记本电脑、鼠标、遥控器、键盘、手机、微波炉、烤箱、烤吐司炉、洗碗槽、冰箱、书、钟表、花瓶、剪刀、泰迪熊、电吹风、牙刷</p>
</div></template>


