export const data = JSON.parse("{\"key\":\"v-2f1bb992\",\"path\":\"/netty/basics/summary.html\",\"title\":\"Netty概述\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Netty概述\",\"author\":\"vingkin\",\"date\":\"2022-07-22T00:00:00.000Z\",\"description\":\"Netty 是什么？ Netty is an asynchronous event-driven network application framework for rapid development of maintainable high performance protocol servers &amp; clients.\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vingkin.github.io/Blog/netty/basics/summary.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Vingkin的学习博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Netty概述\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Netty 是什么？ Netty is an asynchronous event-driven network application framework for rapid development of maintainable high performance protocol servers &amp; clients.\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"vingkin\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-07-22T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Netty概述\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-07-22T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"vingkin\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Netty 是什么？\",\"slug\":\"netty-是什么\",\"link\":\"#netty-是什么\",\"children\":[]},{\"level\":2,\"title\":\"Netty 的作者\",\"slug\":\"netty-的作者\",\"link\":\"#netty-的作者\",\"children\":[]},{\"level\":2,\"title\":\"Netty 的地位\",\"slug\":\"netty-的地位\",\"link\":\"#netty-的地位\",\"children\":[]},{\"level\":2,\"title\":\"Netty 的优势\",\"slug\":\"netty-的优势\",\"link\":\"#netty-的优势\",\"children\":[]}],\"git\":{},\"readingTime\":{\"minutes\":1.25,\"words\":376},\"filePathRelative\":\"netty/basics/summary.md\",\"localizedDate\":\"2022年7月22日\",\"excerpt\":\"<h2> Netty 是什么？</h2>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>Netty is an asynchronous event-driven network application framework\\nfor rapid development of maintainable high performance protocol servers &amp; clients.\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"copyright\":{\"author\":\"vingkin\"},\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
